AWSTemplateFormatVersion: '2010-09-09'
Description: PiVPN infrastructure on Raspberry Pi with dynamic DNS updates.

Parameters:
  HostedZoneId:
    Type: String
    Description: The ID of the zone hosted on Route 53 (e.g. Z0123456789ABC).
  DomainName:
    Type: String
    Description: The full name of the VPN registration (e.g., vpn.mydomain.com).

Resources:
  # 1. Create the initial A record in Route 53
  VPNRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      TTL: '300'
      ResourceRecords:
        - 1.1.1.1 # Initial temporal IP.

  # 2. Create IAM user for raspPI
  PiVPNUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "PiVPN-Updater-${AWS::StackName}"

  # 3. Create AWS credentials (Access Key y Secret Key)
  PiVPNAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref PiVPNUser

  # 4. Minimum permissions policy for updating Route 53
  PiVPNPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PiVPNRoute53UpdatePolicy
      Users:
        - !Ref PiVPNUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - route53:ChangeResourceRecordSets
              - route53:GetHostedZone
              - route53:ListResourceRecordSets
            Resource: !Sub "arn:aws:route53:::hostedzone/${HostedZoneId}"

Outputs:
  AccessKeyId:
    Description: Access Key ID to configure on the Raspberry Pi
    Value: !Ref PiVPNAccessKey
  SecretAccessKey:
    Description: Secret Access Key (Keep it safe!)
    Value: !GetAtt PiVPNAccessKey.SecretAccessKey
  VPNFQDN:
    Description: Domain of your VPN
    Value: !Ref DomainName